services:
  http_server:
    build:
      context: .
      dockerfile: Dockerfile.http
    ports:
      - "8080:8080"
    container_name: http_server
    volumes:
      - ./tmp:/tmp
    entrypoint: ["./http_server", "8080", "/tmp"]

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - "8081:8081"
    container_name: proxy
    entrypoint: ["./proxy", "8081"]
